package com.pickdsm.pickserverspring.domain.application

enum class StatusType {
    DISALLOWED, LEAVE, HOME, FIELD_TRIP, EMPLOYMENT, PICNIC, MOVEMENT, AWAIT,
    PICNIC_REJECT, ATTENDANCE, NOT_COMEBACK, FIELD_TRIP_START, EMPLOYMENT_START,
    DROPOUT,
}
